// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYBUcfPJO6RoWlXgY4rCZXukS1K9BTNhw',
    appId: '1:611416165656:web:01634f46740a071820226d',
    messagingSenderId: '611416165656',
    projectId: 'm-world-71bcf',
    authDomain: 'm-world-71bcf.firebaseapp.com',
    storageBucket: 'm-world-71bcf.firebasestorage.app',
    measurementId: 'G-NQKL0VWJGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4NAEn2qKUu-JlXOV0EY9XhQUX4uzc12U',
    appId: '1:611416165656:android:93947c14ba41e0a720226d',
    messagingSenderId: '611416165656',
    projectId: 'm-world-71bcf',
    storageBucket: 'm-world-71bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4s1OLeStJ0h6x9iqAfb2hNCSzgne4u0',
    appId: '1:611416165656:ios:7181375605cae4d220226d',
    messagingSenderId: '611416165656',
    projectId: 'm-world-71bcf',
    storageBucket: 'm-world-71bcf.firebasestorage.app',
    iosBundleId: 'com.example.mWorld',
  );
}
